package it.polimi.ing.sw.controller;

public enum PlayerState {
    READYTOPLAY, ENDEDTURN, USEDDICE, USEDTOOLCARD, INIZIALIZED,
    FINISHTURN, OFFLINE, SCHEMETOCHOOSE, USEDDICETOOLCARD, FIRSTSTEPTOOLCARD, TURNSTARTED, WAIT,
}
