package it.polimi.ing.sw.controller;

public enum PlayerState {
    READYTOPLAY,ENDEDTURN, CHOOSENTOOLCARD, USEDDICE,USEDTOOLCARD, INIZIALIZED,
    FINISHTURN, OFFLINE,SCHEMETOCHOOSE, USEDDICETOOLCARD, FIRSTSTEPTOOLCARD,
}
